### ISSUE TITLE
Visualization of clusters without cell

### ISSUE THREAD

**Issue by SanderBorgmans** [pyiron/pyiron#391]
When constructing clusters with no cell attribute, the `plot3d()`, `get_final_structure()` and `animate_structure()` do not seem to work (probably some other functions as well). It would be nice to be able to visualize these clusters without cell attribute, since it would be strange to define a unit cell for a cluster object.

If it helps, the `plot3d_ase()` does work for these clusters.

**Comment by sudarsan-surendralal** [comment]
Could you post a simple example notebook here where you generate a cluster? We didn't consider this so far since we mostly work with periodic supercells.

**Comment by SanderBorgmans** [comment]
> Could you post a simple example notebook here where you generate a cluster? We didn't consider this so far since we mostly work with periodic supercells.

No problem. 
[test.zip](https://github.com/pyiron/pyiron/files/3583563/test.zip)

**Comment by sudarsan-surendralal** [comment]
Fixed [here](https://github.com/pyiron/pyiron/pull/393). Defining dummy cells before visualizing in nglview. This does not change the original atom object which still does not have a cell attribute

**Comment by SanderBorgmans** [comment]
Thank you! I'll test it as soon as possible.

**Comment by SanderBorgmans** [comment]
The atoms.py fix seem ok, but the atomistics.py required some tweaking to get both animate_structure and get_structure to work. 

In the definition of trajectory the cells object could also be None, so that len(cells) would fail:
```
        if cells is None or cells[0] is None:
            max_pos = np.max(np.max(positions, axis=0), axis=0)
            max_pos[np.abs(max_pos) < 1e-2] = 10
            cell = np.eye(3) * max_pos
            cells = np.array([cell] * len(positions))

        if len(positions) != len(cells):
            raise ValueError("The positions must have the same length as the cells!")
```

In the definition of get_structure, calling [iteration_step] on the cells object, which could be None throws another error. I suggest:

```
        positions = self.get("output/generic/positions")
        cells = self.get("output/generic/cells")
        
        if cells is None:
            max_pos = np.max(np.max(positions, axis=0), axis=0)
            max_pos[np.abs(max_pos) < 1e-2] = 10
            cell = np.eye(3) * max_pos
            cells = np.array([cell] * len(positions))
            
        snapshot = self.structure.copy()
        snapshot.cell = cells[iteration_step]
        snapshot.positions = positions[iteration_step]
```

**Comment by SanderBorgmans** [comment]
With these alterations, I do still get an error when creating an explicit Atoms object, converting it to a pyiron object, and then calling plot3d() (see jupyter notebook). Plot3d_ase() does not throw an error

[test.zip](https://github.com/pyiron/pyiron/files/3584399/test.zip)

**Comment by sudarsan-surendralal** [comment]
Fixed. I think the cell should stay `None` even in `get_structure()` since it should be compatible with ase. I also disabled showing the cell when it is a cluster.

[test_cluster.zip](https://github.com/pyiron/pyiron/files/3584620/test_cluster.zip)

**Comment by SanderBorgmans** [comment]
This still throws errors for me when there is no cell: https://github.com/pyiron/pyiron/blob/af924b4f0bc0bd76c9220682513bfbe0509fa8c0/pyiron/atomistics/job/atomistic.py#L486

**Comment by SanderBorgmans** [comment]
Also, isinstance(np.array(None),(list,np.ndarray)) this returns True for me. This throws an error for empty cell attribute at https://github.com/pyiron/pyiron/blob/fix_plot3d_clusters/pyiron/atomistics/job/atomistic.py#L490

**Comment by sudarsan-surendralal** [comment]
Oops, my bad!  Can you check this again?

**Comment by SanderBorgmans** [comment]
Now the plot functions seem to be working, but another error pops. When reloading a structure from the hdf5 file, I get the following error, since a cell object is now created in the hdf5 file equal to np.zeros((3,3)) which throws the error:

```
/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/gaussian/gaussian.py in from_hdf(self, hdf, group_name)
     65         with self.project_hdf5.open("input") as hdf5_input:
     66             self.input.from_hdf(hdf5_input)
---> 67             self.structure = Atoms().from_hdf(hdf5_input)
     68 
     69     def visualize_MO(self,index,particle_size=0.5,show_bonds=True):

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in from_hdf(self, hdf, group_name)
    528                 if "cell" in hdf_atoms.list_groups():
    529                     with hdf_atoms.open("cell") as hdf_cell:
--> 530                         self.cell = hdf_cell["cell"]
    531                         self.pbc = hdf_cell["pbc"]
    532 

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in cell(self, value)
    245                 self.set_cell(value, scale_atoms=True)
    246             else:
--> 247                 self.set_cell(value)
    248 
    249     @property

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in set_cell(self, cell, scale_atoms)
   3356         if np.linalg.det(cell) <= 0:
   3357             raise ValueError(
-> 3358                 "Cell must be a full dimensional matrix with " "right hand orientation"
   3359             )
   3360 

ValueError: Cell must be a full dimensional matrix with right hand orientation
```

**Comment by sudarsan-surendralal** [comment]
So this issue has to do with the basic structure of the `Atoms` class and not visualization. So I've opened another pull request that allows having singular matrices for the `cell` value https://github.com/pyiron/pyiron/pull/395. I think these changes should work for you. Do let me know if it doesn't!

**Comment by jan-janssen** [comment]
@SanderBorgmans Is this working now? Can we close the issue?

**Comment by SanderBorgmans** [comment]
@jan-janssen I will let you know when I added the indices to the Gaussian output, this (hopefully) shouldn't take long

**Comment by SanderBorgmans** [comment]
@jan-janssen Should I just add the full structure group from the input to the output? For the moment, I just added the structural properties from the output to the structure group in the ouput file, such as masses, charges, dipoles, ...

**Comment by jan-janssen** [comment]
I am sorry this was a bug on our side - I fixed it in https://github.com/pyiron/pyiron/pull/413

**Comment by SanderBorgmans** [comment]
This fixes the Gaussian issue, but there still seems to be an issue with a cell that is not existent:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-1fae907ed5df> in <module>
      1 from ase import Atoms
      2 #structure = ase_to_pyiron(Atoms(numbers=job.output.numbers,positions=job.output.positions[-1]))
----> 3 structure = job.get_structure(-1)
      4 structure.plot3d()

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/job/atomistic.py in get_structure(self, iteration_step, wrap_atoms)
    658             snapshot.indices = indices[iteration_step]
    659         if wrap_atoms:
--> 660             return snapshot.center_coordinates_in_unit_cell()
    661         else:
    662             if len(self.output.unwrapped_positions) > max([iteration_step, 0]):

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in center_coordinates_in_unit_cell(self, origin, eps)
   1057         """
   1058         self.set_scaled_positions(
-> 1059             np.mod(self.get_scaled_positions(wrap=False) + eps, 1) - eps + origin
   1060         )
   1061         return self

/scratch/gent/419/vsc41947/nanoscale/anaconda3/envs/pysqa/lib/python3.7/site-packages/pyiron/atomistics/structure/atoms.py in set_scaled_positions(self, scaled)
   3304         """
   3305         if self.cell is None:
-> 3306             raise ValueError("cell has not been set yet")
   3307         self.positions = np.einsum("jk,ij->ik", self.cell, scaled)
   3308 

ValueError: cell has not been set yet

**Comment by jan-janssen** [comment]
@chandu can you take a look at this?

**Comment by sudarsan-surendralal** [comment]
Fixed it here https://github.com/pyiron/pyiron/pull/414. The issue is that the `center_coordinates_in_unitcell()` command should only work if a cell is defined. Do let me know if this is fixed now.

**Comment by SanderBorgmans** [comment]
@sudarsan-surendralal It seems that now everything is working! Thank you for all the efforts! I will keep you posted on any other issues I might run into with these cluster structures. I will close the issue for now.
