### ISSUE TITLE
SPHInX fails when submitted without calc_static()

### ISSUE THREAD

**Issue by samwaseda** [pyiron/pyiron#769]
The following cell doesn't work:

```
spx = pr.create_job('Sphinx', 'spx')
spx.structure = pr.create_structure('Al', 'fcc', 4)
# spx.calc_static()
spx._create_job_structure()
spx = pr.load('spx')
spx.run()
```

And I realised when `spx.calc_static()` is called beforehand, it works fine. Also, if the job is not submitted (i.e. without reloading), it works fine as well. Since the error message gives no clue what is the problem, it should at least complain if the job is submitted without `calc_static` (which can be included in `def check_setup`, but I don't know how to check whether `calc_static` was called beforehand or not).

**Comment by pmrv** [comment]
Will have a look tonight.

**Comment by samwaseda** [comment]
I figured out that it's not just about `calc_static`. Actually when the system is magnetic **and** used as a reference job, the labels are not output properly. Here's an example that fails:

```
spx = pr.create_job('Sphinx', 'spx')
spx.structure = pr.create_structure('Fe', 'bcc', 2)
spx.structure.set_initial_magnetic_moments([2, 2])
spx.server.run_mode.interactive = True
spx.calc_static()
sxextopt = pr.create_job('SxExtOptInteractive', 'sxextopt')
sxextopt.ref_job = spx

sxextopt._create_job_structure()
sxextopt = pr.load('sxextopt')
sxextopt.run()
```

Apparently the problem is related to `job._spin_enabled`, which stays `False` even though it shouldn't.

**Comment by samwaseda** [comment]
> I figured out that it's not just about `calc_static`. Actually when the system is magnetic **and** used as a reference job, the labels are not output properly. Here's an example that fails:
> 
> ```
> spx = pr.create_job('Sphinx', 'spx')
> spx.structure = pr.create_structure('Fe', 'bcc', 2)
> spx.structure.set_initial_magnetic_moments([2, 2])
> spx.server.run_mode.interactive = True
> spx.calc_static()
> sxextopt = pr.create_job('SxExtOptInteractive', 'sxextopt')
> sxextopt.ref_job = spx
> 
> sxextopt._create_job_structure()
> sxextopt = pr.load('sxextopt')
> sxextopt.run()
> ```
> 
> Apparently the problem is related to `job._spin_enabled`, which stays `False` even though it shouldn't.

This problem is now fixed [here](https://github.com/pyiron/pyiron/pull/770)

**Comment by samwaseda** [comment]
I realized that when the job is submitted to the queue, it works also properly. The problem was apparently related to `validate_ready_to_run`, which is obviously not called with the lines above, but it seems to be called on the queue. Maybe @jan-janssen can explain what was happening, but as my problem has been solved (it was more related to the spin problem that I already fixed [here](https://github.com/pyiron/pyiron/pull/770)), I close this issue.

**Comment by pmrv** [comment]
The first cell is still broken for me on 3982152b.  I guess this has something to do with how the default values are checked after the job is loaded from hdf5.

**Comment by jan-janssen** [comment]
`spx._create_job_structure()` is an internal function - so I am not sure if we want to support this officially. I am aware that I originally introduced it to debug the queuing system, but maybe it makes more sense to write a different wrapper. The function is defined here: https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/generic.py#L1592 and typically called in `_run_if_new(0` https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/generic.py#L1326 which also contains `validate_ready_to_run()`. 

So I guess the above example works if you use: 
```
spx = pr.create_job('Sphinx', 'spx')
spx.structure = pr.create_structure('Al', 'fcc', 4)
# spx.calc_static()
spx.validate_ready_to_run()
spx._create_job_structure()
spx = pr.load('spx')
spx.run()
```

I was not aware that `validate_ready_to_run()` is changing the input of the sphinx job. But I guess the easiest way is to introduce just a new function, something like: 
```
def save_for_running_later(self):
     self.validate_ready_to_run()
     self._create_job_structure()
```

**Comment by samwaseda** [comment]
> `spx._create_job_structure()` is an internal function - so I am not sure if we want to support this officially. I am aware that I originally introduced it to debug the queuing system, but maybe it makes more sense to write a different wrapper. The function is defined here: https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/generic.py#L1592 and typically called in `_run_if_new(0` https://github.com/pyiron/pyiron/blob/master/pyiron/base/job/generic.py#L1326 which also contains `validate_ready_to_run()`.
> 
> So I guess the above example works if you use:
> 
> ```
> spx = pr.create_job('Sphinx', 'spx')
> spx.structure = pr.create_structure('Al', 'fcc', 4)
> # spx.calc_static()
> spx.validate_ready_to_run()
> spx._create_job_structure()
> spx = pr.load('spx')
> spx.run()
> ```
> 
> I was not aware that `validate_ready_to_run()` is changing the input of the sphinx job. But I guess the easiest way is to introduce just a new function, something like:
> 
> ```
> def save_for_running_later(self):
>      self.validate_ready_to_run()
>      self._create_job_structure()
> ```

Shouldn't this be called `save()` and change the existing `save()` to `_save()`?

**Comment by pmrv** [comment]
Calling `save()` already works like this (except #765).

**Comment by samwaseda** [comment]
At least I'd find it very confusing if there were `save_for_running_later` and `save` at the same time (regarding auto complete), while `save` is not meant to be used by the user.

**Comment by pmrv** [comment]
I think the issue is that `_create_job_structure()` changes the job status to `created`. Probably that confuses the default logic later on running, so that it doesn't add the default sphinx commands as it thinks they're already created.  Since the cell works using `save()` and `_create_job_structure()` is not a user-facing function, I'd think this is a non-issue.

**Comment by jan-janssen** [comment]
@samwaseda I agree we can call it `save()` because `_create_job_structure()` currently internally calls the save - but we have to be careful with the refactoring. 

@pmrv A job which has a job id should always have the status `created`. At this point we assume the HDF5 file exists and the input files are written, calling `save()` in the current implementation might be error-prone.

**Comment by pmrv** [comment]
@jan-janssen Fair, then we need to look into why the default sphinx config is written but not reflected in the inputlist/hdf.  I also agree with @samwaseda that `save()` should have an underscored name then.

**Comment by jan-janssen** [comment]
I updated the save function in https://github.com/pyiron/pyiron/pull/771
